### ISSUE TITLE
possible to use without specs2?

### ISSUE THREAD

**Issue by fommil** [djspiewak/smock#2]
e.g. if I wanted to use scalatest

**Comment by djspiewak** [comment]
@fommil Sorry didn't see this until just now.  It's possible to generalize the framework so that it works with both specs2 and scalatest.  I've done things like that in the past, though it does tend to make the build absolutely bonkers since you're adding a dimension of cross-publication.

In general, what you need to do is generalize the mechanism for producing test failures at a particular location.  ScalaTest actually has a much nicer (implicit-driven) mechanism for doing this, so it's generally specs2 that requires the extra fiddling.  The way I've done this in the past is characterize the line-specific failure production using a typeclass which has an implementation for each test framework, and that implementation is naturally defined by a subproject.

I would eagerly accept a PR which does this, but right now I don't really have the need or the time to do it.
